### PR TITLE
add support for 1,2 and 3d trusses with simple tests

### PR DESCRIPTION
**Pull request by jtveiten**
I think this is ok for the truss itself. Now I need to know how to setup forces and boundary conditions

### CODE REVIEW

**Comment by ahojukka5** [comment]
Do you have some example structure in your mind we could use as an example on documentation?

**Comment by jtveiten** [comment]
Something like these could be easy starters:
The simplest would be a truss system of two bars (45 deg) with one or 2 forces, support fixed in both directions

image




The other would be three trusses in a triangle (45 deg) with a rotated support aligned with the diagonal truss and a horizontal load

image

It would be good to solve the system, print out truss forces, support forces, displacements etc

**Comment by ahojukka5** [comment]
Actually the support of the first example is not so easy as it's in 45 degrees, it's a multipoint constraint.

**Comment by jtveiten** [comment]
Yes, I added the rotated support test as a reminder of something we need down the road. 
But simple support conditions are sufficient to start with, so a couple of smaller/larger systems can be made as tests/examples.

**Comment by ahojukka5** [comment]
Anyway let's just merge this if everything is working. We can make those examples in documentation to verify results.

**Pull request merged**
